projectrater/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('ratings.urls')),
    path('api-auth/', include('rest_framework.urls'))
]

ratings/urls.py
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
  url(r'^$', views.ProjectListView.as_view(), name='homepage'),
  url(r'register', views.register_user, name='register'),
  url(r'login', views.login_user, name='login'),
  url(r'logout', views.logout_user, name='logout'),
  url(r'new/project/$', views.ProjectCreateView.as_view(), name='project_add'),
  #url(r'^profile/(?P<user_id>\d+)', views.profile, name='profiles'),
  url(r'profile/', views.profile, name='profileupdate'),
  url(r'update_profile', views.update_profile, name='update_profile'),
  url(r'^api/project/$', views.ListProjects.as_view()),
  url(r'^api/profile/$', views.ListUserProfile.as_view()),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ratings/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date
from PIL import Image


# Create your models here.
class Project(models.Model):
  title = models.CharField(max_length=70)
  image = CloudinaryField('image', default='photo.jpeg')
  description = models.TextField(default='project description here')
  link = models.URLField(max_length=300, default='https://appname.herokuapp.com/')
  username = models.ForeignKey(User,on_delete=models.CASCADE)
  rating = models.ForeignKey('Rating',on_delete=models.CASCADE, null=True, blank=True)

  class Meta:
    ordering = ['title']

  def __str__(self):
    return self.title

  def save_project(self):
    self.save()


  def delete_project(self):
    self.delete()

  def get_absolute_url(self):
    return reverse('homepage')


class Rating(models.Model):
  design = models.IntegerField(default=0)
  usability = models.IntegerField(default=0)
  content = models.IntegerField(default=0)

  def __str__(self):
    return str(self.id)


class Profile(models.Model):
  user = models.OneToOneField(User,on_delete=models.CASCADE)
  bio = models.TextField(max_length=500, blank=True)
  location = models.CharField(max_length=50, blank=True)
  occupation = models.CharField(max_length=70, blank=True)
  date_updated = models.DateField(default=date.today)
  profile_picture = CloudinaryField('image', blank=True)
  project = models.ForeignKey('Project', on_delete=models.CASCADE, null=True, blank=True)
  def __str__(self):
    return self.user.username

  def save(self,*args,**kwargs):
    super().save()
    img = Image.open(self.profile_picture)
    if img.height > 100 or img.width >100:
      new_img = (100,100)
      img.thumbnail(new_img)
      img.save(self.profile_picture)

  def get_absolute_url(self):
    return reverse('profileupdate')

  def save_profile(self):
    self.save()

ratings/forms.py
from django.db.models import fields
from django.forms.models import model_to_dict
from ratings.models import Profile,Project
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

#Your forms here
class NewUserForm(UserCreationForm):
  email = forms.EmailField()

  class Meta:
    model = User
    fields = ("username", "email", "password1", "password2")


  def save(self,commit=True):
    user = super(NewUserForm, self).save(commit=False)
    user.email = self.cleaned_data['email']
    if commit:
      user.save()
    return user


class UpdateUserForm(forms.ModelForm):
  class Meta:
    model = User
    fields = ['username', 'email']


class ProfileForm(forms.ModelForm):
  class Meta:
    model = Profile
    fields = ('profile_picture','user','bio','location','occupation')


class UploadProjectForm(forms.ModelForm):
  class Meta:
    model = Project
    fields = ('title','image','description','link','rating')

ratings/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from .forms import NewUserForm, ProfileForm,UploadProjectForm,UpdateUserForm
from django.contrib.auth.models import User
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializer import ProfileSerializer,ProjectSerializer
from .models import Project,Profile
from rest_framework import authentication, permissions, serializers
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.contrib.messages.views import SuccessMessageMixin

# Create your views here.
def index(request):
  message = "Welcome to Rate-My-Project"
  return render(request,'index.html',{"message": message})


def register_user(request):
  if request.method == "POST":
    form = NewUserForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      messages.success(request, f'Registration Successful.')
      return redirect('homepage')
    messages.error(request, f'Unsuccessful registration. Invalid information.')
  form = NewUserForm()
  return render(request, 'registration/registration_form.html', {"registration_form": form})


def login_user(request):
  if request.method == 'POST':
    form = AuthenticationForm(request, data=request.POST)
    if form.is_valid():
      username = form.cleaned_data.get('username')
      password = form.cleaned_data.get('password')
      user = authenticate(username=username,password=password)
      if user is not None:
        login(request, user)
        messages.info(request, f"You are now logged in as {username}.")
        return redirect('homepage')
      else:
        messages.error(request, f'Invalid Username or password')
    else:
      messages.error(request, f'Invalid username or password')
  form = AuthenticationForm()
  return render(request, 'registration/login_form.html', {"login_form": form})


def logout_user(request):
  logout(request)
  messages.info(request, f'You have successfully logged out.')
  return redirect('login')


@login_required
def profile(request):
  # user = User.objects.get()
  # user.save()
  return render(request,'profile/profile.html')

@login_required
#@transaction.atomic
def update_profile(request):
  if request.method == 'POST':
    user_form = UpdateUserForm(request.POST, instance=request.user)
    profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
    if user_form.is_valid() and profile_form.is_valid():
      user_form.save()
      profile_form.save()
      messages.success(request, 'Your profile was successfully updated!')
      return redirect('profileupdate')
    else:
      messages.error(request,f'Please try updating your profile again.')
  else:
    user_form = UpdateUserForm(instance=request.user)
    profile_form = ProfileForm(instance=request.user.profile)
  return render(request,'profile/update_profile.html',{"profile_form":profile_form, "user_form": user_form, "prolife_form":profile_form})


class ListProjects(APIView):
  """
    View to list all users in the system.

    * Requires token authentication.
    * Only admin users are able to access this view.
  """
  # authentication_classes = [authentication.TokenAuthentication]
  # permission_classes = [permissions.IsAuthenticatedOrReadOnly]
  queryset = Project.objects.all()
  
  def get(self,request,format=None):
    all_projects = Project.objects.all()
    serializers = ProjectSerializer(all_projects, many=True)
    return Response(serializers.data)


class ListUserProfile(APIView):
  # authentication_classes = [authentication.TokenAuthentication]
  # permission_classes = [permissions.IsAuthenticatedOrReadOnly]
  queryset = Profile.objects.all()

  def get(self,request,format=None):
    profile_details = Profile.objects.all()
    serializers = ProfileSerializer(profile_details, many=True)
    return Response(serializers.data)


class ProjectCreateView(LoginRequiredMixin,CreateView):
  form_class = UploadProjectForm
  template_name = 'new_project.html'

  def form_valid(self, form):
    form.instance.username = self.request.user
    return super().form_valid(form)


class ProjectListView(ListView):
  model = Project
  template_name = 'index.html'

ratings/templates/all_ratings/base.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    {% if title %}
    <title> Rate-My-Project - {{title}} </title>
    {% else %}
      <title>Rate-My-Project</title>
    {% endif %}

    {% block styles %}
      {% bootstrap_css %}
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    {% endblock %}
  </head>
  <body>

    {% include 'navbar.html' %}

    {% block content %} <h2 class="text-center"> Your Projects Here: {% endblock %} </h2>

    {% block scripts %}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
            {% bootstrap_javascript %}
        {% endblock %}
  </body>
</html>

ratings/templates/index.html
{% extends 'all_ratings/base.html' %} 

{% block content %}  

<div class="container">
  <div class="row">
    {% for project in project_list %}
    <!-- <ul> -->
    <div class="col-md-3">
      <div class="card my-2">
        <img src="{{project.image.url}}" class="img-thumbnail" alt="">
        <div class="card-body">
          <h6 class="card-title">{{project.title}}</h6>
          <p class="fs-6 fw-light">{{project.description}}</p>
          <a href="{{project.link}}" class="btn btn-sm btn-primary" target="_blank">Visit Website</a>
        </div>
      </div>
    </div>
  <!-- </ul> -->
    {% endfor %}
  </div>
</div>

{% endblock %}
<!-- <div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div> -->

ratings/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand text-light" href="{% url 'homepage' %}">Rate-My-Project</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">


          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="fas fa-home text-light" style="margin-left:100%; font-size:15px" aria-current="page" href="{% url 'homepage' %}"></a>
            </li>
          </ul>

          <form  style="margin-left:5%;" role="search" action="">
            <div class="input-group-sm">
              <input class="form-control-sm"  type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-secondary btn-sm" style="margin-left:-6px" id="button-addon2" type="submit">Search</button>
            </div>
          </form>


          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="fas fa-upload nav-link text-light" style="margin-left:30px" aria-current="page" href="{% url 'project_add' %}"></a>
            </li>
          </ul>

          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">Submit Your Projects
              <a class="fas fa-user-circle nav-link text-light" aria-current="page" href="{% url 'profileupdate' %}"></a>
            </li>
          </ul>

          <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %} 
            <li class="nav-item">
              <a class="fas fa-sign-out-alt nav-link text-light" href="/logout"></a>
            </li>
            {% else %} 
            <li class="nav-item">
              <a class="nav-link text-light" href="/login">Login</a>
            </li>
            {% endif %}
          </ul>

        </div>
      </div>
    </nav>
  </body>
</html>

ratings/templates/new_project.html
{% extends 'all_ratings/base.html' %}

{% load crispy_forms_tags %} 

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %} 
          <fieldset class="form-group">
            <legend class="border-bottom mb-4">Submit a Project</legend>
              {{ form | crispy }}
          </fieldset>
          <div class="form-group">
            <input type="submit" class="btn btn-success btn-lg" value="Submit">
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

ratings/templates/profile/base.html
{% load bootstrap5 %} 


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">

    {% if title %} 
    <title>{{title}}</title>
    {% endif %} 

    {% block styles %}
      {% bootstrap_css %}
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    {% endblock %}
  </head>
  <body>

    {% include 'navbar.html' %}

    {% block content %} {% endblock %} 

    {% block scripts %} 
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
      {% bootstrap_css %}
    {% endblock %} 

  </body>
</html>

ratings/templates/profile/profile.html
{% extends 'profile/base.html' %} 

{% block title %}Profile Page{% endblock title %}

{% block content %}

<div class="container">
  <h2 class="text-center">Here's your profile page {{user.username}}</h2>
  <ul>
    <li>Location: {{user.profile.location}}</li>
    <li>Occupation: {{user.profile.occupation}}</li>
    <li>Bio: {{user.profile.bio}}</li>
    <li>Date created: {{user.profile.date_updated}}</li>
  </ul>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <a class="btn btn-primary btn-lg" role="button" aria-current="page" href="{% url 'update_profile' %}">Update Profile</a>
    </div>
  </div>
</div>


{% endblock %}

ratings/templates/profile/update_profile.html
{% extends 'profile/base.html' %} 

{% load crispy_forms_tags %}

{% block title %}Update Profile{% endblock %} 

{% block content %} 


<!-- User Update Form -->
<div class="row my-3 p-3">
  <img class="rounded-circle account-img" src="{{ user.profile.profile_picture.url }} " style="cursor: pointer;"/>
</div>

<!-- Update Profile Form -->
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h4>Update Profile</h4>
      <form action="{% url 'update_profile' %}" method="post">
        {% csrf_token %} 


        {{ profile_form | crispy }}

        <button class="btn btn-primary btn-sm" type="submit">Save Changes</button>
        <button class="btn btn-dark btn-sm" type="reset">Reset</button>
      </form>
    </div>
  </div>
</div>


{% endblock %}